<a href="https://colab.research.google.com/github/gsurend4/BackPropogration/blob/main/01_Pytorch_workflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

from torch import nn

import matplotlib.pyplot as plt

torch.__version__

'2.9.0+cu126'

## Workflow

1. Data (prepare and load)
2. Build Model
3. Fitting the Model to the data (Model Training)
4. Making Predictions and Evaluating the Model (Model Evaluating)
5. Saving and Loading the Model
6. Putting all together

## 01. Data (Preparation and Loading)

In [2]:
# parameters
weight = 0.7
bias = 0.3

# Linear Regression Model --> y = mx + b
start = 0
end = 1
step = 0.02

X = torch.arange(start, end, step).unsqueeze(dim=1) # increasing 1 dim

y = weight * X + bias

# X, y

In [3]:
len(X), len(y)

(50, 50)

In [4]:
# Splitting the data : Training data vs Test data

train_split = int(0.8 * len(X))
# 40 data

X_train, y_train = X[:train_split], y[:train_split]

X_test, y_test = X[train_split:], y[train_split:]


Plotting the data points

In [40]:
def data_plot(train_data = X_train,
              train_labels = y_train,
              test_data = X_test,
              test_labels = y_test,
              predictions = None):

    plt.figure(figsize = (10,7))

    plt.scatter(train_data, train_labels, c = 'b', s = 4, label = 'train_data')

    plt.scatter(test_data, test_labels, c = 'g', s = 4, label = 'test_data')

    if predictions is not None:
        plt.scatter(test_data, predictions.detach().numpy(), c = 'r', s = 4, label = 'predictions')

    plt.legend()

In [6]:
data_plot()

## 02. Build Model

In [34]:
class LinearRegressionModel(nn.Module): # Inheritance
    def __init__(self):
        super().__init__()
        #  nn.Parameter --> automatically added to the list of the Model parameters
        self.weights = nn.Parameter(torch.randn(1,
                                   requires_grad=True,
                                   dtype = torch.float))
        self.bias = nn.Parameter(torch.randn(1,
                                requires_grad=True,
                                dtype = torch.float))
    # forward pass
    def forward(self, x:torch.Tensor) -> torch.Tensor: # return type is also torch.Tensor
        return self.weights * x + self.bias # Regression formula y = mx + b

    # return value
    def __repr__(self) -> str:
        return "Custom Linear Model"

In [35]:
# First Model Creation

# random seed to have constant value
torch.manual_seed(42)

# Instance of the Model
model_0 = LinearRegressionModel()

list(model_0.parameters())

[Parameter containing:
 tensor([0.3367], requires_grad=True),
 Parameter containing:
 tensor([0.1288], requires_grad=True)]

In [42]:
# Dictionary format Parameter Value -- Easy to see parameters

model_0.state_dict()

OrderedDict([('weights', tensor([0.3367])), ('bias', tensor([0.1288]))])

In [37]:
y_preds = model_0(X_test) # or model_0.forward(X_test) --> Pytorch internally implements __call__ methods which calls the forward method.

# Actual result
y_preds

tensor([[0.3982],
        [0.4049],
        [0.4116],
        [0.4184],
        [0.4251],
        [0.4318],
        [0.4386],
        [0.4453],
        [0.4520],
        [0.4588]], grad_fn=<AddBackward0>)

In [38]:
# Expected Result
y_test

tensor([[0.8600],
        [0.8740],
        [0.8880],
        [0.9020],
        [0.9160],
        [0.9300],
        [0.9440],
        [0.9580],
        [0.9720],
        [0.9860]])

In [41]:
data_plot(predictions=y_preds)